- name: Create Seed Jobs
  hosts: localhost
  roles:
    - jobs
  vars:
    folders:
      - { name: "expense-project" }
      - { name: "expense-project/CI-Jobs" }
      - { name: "expense-project/Infra-Jobs" }


