- name: Create Seed Jobs
  hosts: localhost
  roles:
    - jobs
  vars:
    folders:
      - { name: "expense-project" }
      - { name: "expense-project/CI-Jobs" }
      - { name: "expense-project/Infra-Jobs" }
    multibranch_jobs:
      - { name: "expense-backend", folder: "expense-project/CI-Jobs", repo: "https://github.com/vijayavanisabbiti/expense-backend", filename: "Jenkinsfile" }
      - { name: "expense-frontend", folder: "expense-project/CI-Jobs", repo: "https://github.com/vijayavanisabbiti/expense-frontend", filename: "Jenkinsfile" }
    singlebranch_jobs:
      - { name: "expense-ansible", folder: "expense-project/Infra-Jobs", repo: "https://github.com/vijayavanisabbiti/expense-ansible", filename: "Jenkinsfile" }
      - { name: "expense-terraform", folder: "expense-project/Infra-Jobs", repo: "https://github.com/vijayavanisabbiti/expense-terraform", filename: "Jenkinsfile" }


