- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/folder.xml') }}"
    name: "{{item.name}}"
    password: IluMachre@123
    url: http://54.204.251.231:8080
    user: admin
  loop: "{{ folders }}"

- name: Create Multi Branch Pipelines
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/multibranchjob.xml') }}"
    name: "{{item.folder}}/{{item.name}}"
    password: IluMachre@123
    url: http://54.204.251.231:8080
    user: admin
  loop: "{{ multibranch_jobs }}"

- name: Create Single Branch Pipelines
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/singlebranchjobs.xml') }}"
    name: "{{item.folder}}/{{item.name}}"
    password: IluMachre@123
    url: http://54.204.251.231:8080
    user: admin
  loop: "{{ singlebranch_jobs }}"


