- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item.name}}"
    password: IluMachre@123
    url: http://54.234.132.221:8080
    user: admin
  loop: "{{ folders }}"


