- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: test
    password: IluMachre@123
    url: http://54.234.132.221:8080
    user: admin

- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/folder.xml') }}"
    name: expense-project
    password: IluMachre@123
    url: http://54.234.132.221:8080
    user: admin